services:
  goma-gateway:
    image: jkaninda/goma-gateway
    command: server -c goma.yaml
    healthcheck:
      test: curl -f http://localhost:80/healthz || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/etc/goma/
      - ./letsencrypt:/etc/letsencrypt

