services:
  goma-gateway:
    image: jkaninda/goma-gateway
    command: server
    healthcheck:
      test: curl -f http://localhost/healthz || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - "80:80"
    volumes:
      - ./config:/config/