services:
  goma-gateway:
    image: jkaninda/goma-gateway:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/etc/goma
      - providers:/etc/goma/providers
    environment:
      -  GOMA_LOG_LEVEL=info
      -  GOMA_EXTRA_CONFIG_DIR=/etc/goma/providers
      -  GOMA_EXTRA_CONFIG_WATCH=true
      -  GOMA_ENTRYPOINT_WEB_ADDRESS=[::]:80
      -  GOMA_ENTRYPOINT_WEB_SECURE_ADDRESS=[::]:443
    networks:
      - goma-net

  goma-provider:
    image: jkaninda/goma-docker-provider
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Required
      - providers:/etc/goma/providers
    environment:
      - GOMA_OUTPUT_DIR=/etc/goma/providers # Optional, default /etc/goma/providers
      - GOMA_ENABLE_SWARM=false # Enable Swarm mode, default false
    networks:
      - goma-net
  # Web Service - Minimal Configuration
  web-service:
    image: jkaninda/okapi-example
    labels:
      - "goma.enable=true"
      - "goma.port=8080"
      - "goma.hosts=example.com, www.example.com"
    networks:
      - goma-net
volumes:
  providers: {}
networks:
  goma-net:
    driver: bridge