##### Extra Middlewares
middlewares:
  # Enables Basic Authentication for specified paths
  - name: extra-basic-auth
    # Authentication type (supported types: jwt, basic, OAuth)
    type: basic
    # Define paths that require authentication
    paths:
      - /user
      - /admin
      - /account
    # Authentication credentials for basic authentication
    rule:
      username: admin
      password: admin

  # Blocks access to sensitive or restricted paths, returning a 403 Forbidden response
  - name: extra-api-forbidden-paths
    # Middleware type for access control
    type: access
    # Define paths to restrict access
    paths:
      - /swagger-ui/*
      - /v2/swagger-ui/*
      - /api-docs/*
      - /internal/*
      - /actuator/*

##### Extra Routes
routes:
  # Example route configuration
  - path: /extra
    # name for the route
    name: extra
    # Hosts (domains) for host-based routing (optional)
    hosts: []
    # Rewrites the request path to a new destination path
    # Example: rewrite "/store" to "/"
    rewrite: /
    # Defines the backend service destination for this route
    destination: https://example.com
    # Specifies allowed HTTP methods for this route
    methods: [POST, PUT, GET]
    # Disables proxy host forwarding (if false, Host header is forwarded)
    disableHostForwarding: false
    # Configure route-specific CORS settings (overrides global CORS)
    cors:
      # Define allowed origins for this route
      origins:
        - https://dev.example.com
        - http://localhost:3000
        - https://example.com
      # Define CORS headers specific to this route
      headers:
        Access-Control-Allow-Methods: 'GET'
        Access-Control-Allow-Headers: 'Origin, Authorization, Accept, Content-Type, Access-Control-Allow-Headers, X-Client-Id, X-Session-Id'
        Access-Control-Allow-Credentials: 'true'
        Access-Control-Max-Age: 1728000
