## Example of Advanced Kubernetes Deployment

### Requirements
#- **Custom Resource Definitions (CRDs)** and the **Goma Gateway Operator**.
#    - Kubernetes Operator: [Goma Operator](https://github.com/jkaninda/goma-operator)
#    - CRD doc: https://doc.crds.dev/github.com/jkaninda/goma-operator

---

### Middleware Configuration
apiVersion: gomaproj.github.io/v1beta1
kind: Middleware
metadata:
  name: basic-middleware-sample
spec:
  type: basic
  paths:
    - /admin # Blocks only /admin
    - /admin/*  # Explicitly blocks /admin and all subpaths
  rule:
    realm: your-realm # Optional
    users:
      - admin:{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc= # SHA-1 hash
      - admin:$2a$12$LaPhf23UoCGepWqDO0IUPOttStnndA5V8w7XPNeP0vn712N5Uyali # bcrypt hash
      - admin:admin # Plaintext password
---
## Gateway
apiVersion: gomaproj.github.io/v1beta1
kind: Gateway
metadata:
  name: gateway-sample
spec:
  # Goma Gateway image
  imageName: jkaninda/goma-gateway:latest # https://github.com/jkaninda/goma-gateway/releases
  ## Server Configuration
  server:
    tlsSecretName: '' # Optional: Specify a Kubernetes TLS secret name
    redis:
      addr: '' # Optional: Redis host (e.g., redis:6379)
      password: '' # Optional: Redis password
    writeTimeout: 10 # Request write timeout in seconds
    readTimeout: 15  # Request read timeout in seconds
    idleTimeout: 30  # Idle timeout in seconds
    logLevel: info   # Logging level (e.g., info, debug, warn, error)
    disableHealthCheckStatus: false # Enable or disable health check status
    disableKeepAlive: false         # Enable or disable KeepAlive connections
    enableMetrics: true             # Enable Prometheus metrics for monitoring

  ## Scaling and Resource Management
  replicaCount: 1 # Number of initial replicas
  resources:
    limits:
      cpu: 200m    # Maximum CPU allocation
      memory: 512Mi # Maximum memory allocation
    requests:
      cpu: 100m    # Minimum CPU allocation
      memory: 128Mi # Minimum memory allocation
  autoScaling:
    enabled: true # Enable Horizontal Pod Autoscaler
    minReplicas: 2 # Minimum number of replicas
    maxReplicas: 5 # Maximum number of replicas
    targetCPUUtilizationPercentage: 80 # Target CPU utilization
    targetMemoryUtilizationPercentage: 80 # Target memory utilization

  ## Node Affinity
  affinity: {}
---
## Route
apiVersion: gomaproj.github.io/v1beta1
kind: Route
metadata:
  name: route-sample
spec:
  # Name of the associated gateway
  gateway: gateway-sample
  disabled: false                # Disabled specifies whether the route is disabled, the route will not be proxied.
  # Route Configuration
  path: / # URL path for the route
  hosts: [] # Optional: Hostnames/domains for routing
  rewrite: / # Rewrite the path (e.g., /store -> /)
  methods:
    - GET
    - POST
    - PUT

  # Backend Configuration
  destination: https://example.com # Primary destination URL
  backends: [] # Optional: Additional backends for load balancing
  insecureSkipVerify: false # Skip TLS verification (not recommended)

  # Health Check Settings
  healthCheck:
    path: / # Health check endpoint
    interval: 10s # Check interval
    timeout: 10s # Timeout for health check
    healthyStatuses:
      - 200 # HTTP status codes indicating healthy responses
      - 404

  # Cross-Origin Resource Sharing (CORS) Configuration
  cors:
    origins: [] # Allowed origins
    headers: {} # custom headers

  # Security and Middleware
  disableHostForwarding: true # Disable forwarding of Host headers
  blockCommonExploits: false  # Enable or disable blocking of common exploits
  # List of middleware names
  middlewares:
    - basic-middleware-sample
