name: Bin release
on:
  release:
    types: [created]

# contents: write is needed to attach binaries to the release. packages is not
# used by this workflow.
permissions:
  contents: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Get the tag name
        id: get_tag_name
        run: |
          # Extract tag name and remove "v" if present
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG_NAME#v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo BUILD_TIME=$(date) >> ${GITHUB_ENV}
      - uses: wangyoucao577/go-release-action@v1.55
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          # Must be at least the version go.mod requires; go1.25.1 could not
          # compile this module at all.
          goversion: "https://dl.google.com/go/go1.27.0.linux-amd64.tar.gz"
          project_path: "./"
          binary_name: "goma"
          build_flags: -v
          ldflags: -X "github.com/jkaninda/goma-gateway/internal/version.Version=${{ env.VERSION }}" -X "github.com/jkaninda/goma-gateway/internal/version.buildTime=${{ env.BUILD_TIME }}" -X github.com/jkaninda/goma-gateway/internal/version.gitCommit=${{ github.sha }}
          #extra_files: LICENSE README.md